apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vortex.fullname" . }}-apollo
  labels:
    app.kubernetes.io/name: {{ include "vortex.name" . }}
    helm.sh/chart: {{ include "vortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    io.h5k.vortex/component: apollo
spec:
  replicas: {{ .Values.apollo.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vortex.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      io.h5k.vortex/component: apollo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vortex.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        io.h5k.vortex/component: apollo
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.apollo.deployment.image.repository }}:{{ .Values.apollo.deployment.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /graphql
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /graphql
          #     port: http
          resources:
            {{- toYaml .Values.apollo.deployment.resources | nindent 12 }}
      {{- with .Values.apollo.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.apollo.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.apollo.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
