apiVersion: v1
kind: Service
metadata:
  name: {{ include "vortex.fullname" . }}-apollo
  labels:
    app.kubernetes.io/name: {{ include "vortex.name" . }}
    helm.sh/chart: {{ include "vortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    io.h5k.vortex/component: apollo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "vortex.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    io.h5k.vortex/component: apollo
