apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vortex.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vortex.name" . }}
    helm.sh/chart: {{ include "vortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.js: |
    var config = (() => {
      return {
        "VUE_APP_GRAPHQL_HTTP": "https://apollo.vortex.minikube/graphql",
        "VUE_APP_GRAPHQL_WS": "wss://apollo.vortex.minikube/graphql",
      };
    })();
