apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vortex.fullname" . }}-vue
  labels:
    app.kubernetes.io/name: {{ include "vortex.name" . }}
    helm.sh/chart: {{ include "vortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    io.h5k.vortex/component: vue
spec:
  replicas: {{ .Values.vue.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vortex.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      io.h5k.vortex/component: vue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vortex.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        io.h5k.vortex/component: vue
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "vortex.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.vue.deployment.image.repository }}:{{ .Values.vue.deployment.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
                - name: config-volume
                  mountPath: /usr/share/nginx/html/config.js
                  subPath: config.js
          # livenessProbe:
          #   httpGet:
          #     path: /graphql
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /graphql
          #     port: http
          resources:
            {{- toYaml .Values.vue.deployment.resources | nindent 12 }}
      {{- with .Values.vue.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.vue.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.vue.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
